release:
  draft: true
  prerelease: auto
dist: results
builds:
  - id: oinit
    main: ./cmd/oinit
    binary: oinit
    env:
      - CGO_ENABLED=0
    goos:
      - linux
      - darwin
      - freebsd
    ldflags:
      - -s -w -X main.version={{.Version}} -X main.commit={{.Commit}} -X main.date={{.CommitDate}} -X main.builtBy=goreleaser
    mod_timestamp: "{{.CommitTimestamp}}"

  - id: oinit-ca
    main: ./cmd/oinit-ca
    binary: oinit-ca
    env:
      - CGO_ENABLED=0
    goos:
      - linux
      - darwin
      - freebsd
    ldflags:
      - -s -w -X main.version={{.Version}} -X main.commit={{.Commit}} -X main.date={{.CommitDate}} -X main.builtBy=goreleaser
    mod_timestamp: "{{.CommitTimestamp}}"

  - id: oinit-shell
    main: ./cmd/oinit-shell
    binary: oinit-shell
    env:
      - CGO_ENABLED=0
    goos:
      - linux
      - darwin
      - freebsd
    ldflags:
      - -s -w -X main.version={{.Version}} -X main.commit={{.Commit}} -X main.date={{.CommitDate}} -X main.builtBy=goreleaser
    mod_timestamp: "{{.CommitTimestamp}}"

  - id: oinit-switch
    main: ./cmd/oinit-switch
    binary: oinit-switch
    env:
      - CGO_ENABLED=0
    goos:
      - linux
      - darwin
      - freebsd
    ldflags:
      - -s -w -X main.version={{.Version}} -X main.commit={{.Commit}} -X main.date={{.CommitDate}} -X main.builtBy=goreleaser
    mod_timestamp: "{{.CommitTimestamp}}"

archives:
  - format: tar.gz
    name_template: >-
      {{ .ProjectName }}_
      {{- title .Os }}_
      {{- if eq .Arch "amd64" }}x86_64
      {{- else if eq .Arch "386" }}i386
      {{- else }}{{ .Arch }}{{ end }}
      {{- if .Arm }}v{{ .Arm }}{{ end }}

checksum:
  name_template: "checksums.txt"

snapshot:
  name_template: "{{ incpatch .Version }}-next"

changelog:
  sort: asc
  filters:
    exclude:
      - "^docs:"
      - "^test:"

nfpms:
  - id: oinit
    package_name: oinit
    builds:
      - oinit
    homepage: https://github.com/lbrocke/oinit
    maintainer: Lukas Brocke <lukas@brocke.net>
    description: |-
      Command-line tool to enable federated identities in OpenSSH.
    license: MIT
    formats:
      - deb
      - rpm
    provides:
      - oinit
    overrides:
      deb:
        dependencies:
          - openssh-client
        recommends:
          - oidc-agent
      rpm:
        dependencies:
          - openssh-clients
        recommends:
          - oidc-agent
    deb:
      lintian_overrides:
        - statically-linked-binary
        - changelog-file-missing-in-native-package

  - id: oinit-ca
    package_name: oinit-ca
    builds:
      - oinit-ca
    homepage: https://github.com/lbrocke/oinit
    maintainer: Lukas Brocke <lukas@brocke.net>
    description: |-
      Certificate authority for oinit command-line tool.
    license: MIT
    formats:
      - deb
      - rpm
    provides:
      - oinit-ca
    bindir: /usr/sbin
    contents:
      - src: configs/config.sample.ini
        dst: /etc/oinit-ca/config.ini
        type: config
      - src: init/oinit-ca-packaged.service
        dst: /usr/lib/systemd/system/oinit-ca.service
        type: config
    scripts:
      postinstall: "scripts/oinit-ca-postinstall.sh"
      preremove: "scripts/oinit-ca-preremove.sh"
    deb:
      lintian_overrides:
        - statically-linked-binary
        - changelog-file-missing-in-native-package

  - id: oinit-openssh
    package_name: oinit-openssh
    builds:
      - oinit-switch
      - oinit-shell
    homepage: https://github.com/lbrocke/oinit
    maintainer: Lukas Brocke <lukas@brocke.net>
    description: |-
      oinit programs to integrate with OpenSSH.
    license: MIT
    formats:
      - deb
      - rpm
    provides:
      - oinit-openssh
    bindir: /usr/bin
    overrides:
      deb:
        recommends:
          - openssh-server
          - util-linux
          - motley-cue
      rpm:
        recommends:
          - openssh-server
          - util-linux
          - motley-cue
    scripts:
      postinstall: "scripts/oinit-openssh-postinstall.sh"
      preremove: "scripts/oinit-openssh-preremove.sh"
    deb:
      lintian_overrides:
        - statically-linked-binary
        - changelog-file-missing-in-native-package

dockers:
  - id: oinit-ca
    ids:
      - oinit-ca
    image_templates:
      - "{{ .Env.REGISTRY }}/{{ .Env.IMAGE }}:latest"
      - "{{ .Env.REGISTRY }}/{{ .Env.IMAGE }}:{{ .Tag }}"
    dockerfile: "build/Dockerfile.goreleaser"
    build_flag_templates:
      - "--pull"
      - "--label=org.opencontainers.image.revision={{.FullCommit}}"
      - "--label=org.opencontainers.image.created={{.Date}}"
      - "--label=org.opencontainers.image.version={{.Version}}"
